### ISSUE TITLE
Discrepancy Between net.http_request_queue and net._http_response records

### ISSUE THREAD

**Issue by w3b6x9** [supabase/pg_net#43]
# Bug report

## Describe the bug

There are cases when `net._http_response` would have a subset of records from `net.http_request_queue` even though records from both tables should ideally match.

## Expected behavior

There should be a record in `net._http_response` for every record in `net.http_request_queue` and requests should go through successfully or be marked as failed in `net._http_response`.

## Additional context

Related issue: https://github.com/supabase/supabase/issues/2997

**Comment by steve-chavez** [comment]
IIRC, this issue happened because a user created a foreign key to our queue pk

https://github.com/supabase/pg_net/blob/5ff8b6b6f0d61f4c2ea04e1c2967548474fcd32e/sql/pg_net.sql#L11-L12

Then the TTL would not work because doing DELETEs failed, this would also kill the worker on every restart.

Maybe the correct behavior in this case is to warn instead of crashing - though dying might also be good to avoid having excessive rows in the queue.
