### ISSUE TITLE
some remarks

### ISSUE THREAD

**Issue by RekGRpth** [supabase/pg_net#59]
1) https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L434-L436
No! idle_cb function is called in TopMemoryContext context, and it does not pfree palloc'ed like
https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L452
https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L486
https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L490
etc

**Comment by RekGRpth** [comment]
2) https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L147
https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L360
https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L488
https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L492
https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L510
postgres has own palloc function, so You should not use malloc!

**Comment by RekGRpth** [comment]
3) https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L549
uv library is great! but postgres has own event loop and You should use it like in pg_task
https://github.com/RekGRpth/pg_task/blob/e6b882618e238f05e3a3260ebf43f392ffd8b2c9/work.c#L59-L67
https://github.com/RekGRpth/pg_task/blob/e6b882618e238f05e3a3260ebf43f392ffd8b2c9/work.c#L788

**Comment by RekGRpth** [comment]
4) https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L530
really?! You work under postgres superuser in postgres database?! not-superusers should have power rights to access net.* tables. And how access from another databases? dblink?

**Comment by RekGRpth** [comment]
5) https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L462-L464
how about using `FOR UPDATE SKIP LOCKED`?

**Comment by RekGRpth** [comment]
6) [pg_curl](https://github.com/RekGRpth/pg_curl) with [pg_task](https://github.com/RekGRpth/pg_task) do same as pg_net things and even much more!

**Comment by soedirgo** [comment]
It's been a while since I worked on this so my memory is a bit fuzzy.

> idle_cb function is called in TopMemoryContext context, and it does not pfree palloc'ed

IIRC the start transaction dance automatically creates a transaction-local memory context, so the palloc'd memory should be freed properly.

> postgres has own palloc function, so You should not use malloc!

I don't see why not - using palloc ties the lifetime of the allocated memory to whichever memory context is currently active. I could of course obviate the need for malloc by always switching to TopMemoryContext whenever I wanted to malloc, but using malloc directly makes it clear that it's memory we manage ourselves.

Keep in mind we have 3 systems working together: Postgres, libcurl, and libuv, and for the latter 2 using malloc is at least the well-trodden path.

> uv library is great! but postgres has own event loop

The decision to use libuv was mainly because Postgres's event loop API is not well-documented. Also, using libcurl with libuv is a known use case with [example code](https://github.com/curl/curl/blob/master/docs/examples/multi-uv.c) I can use.

We did end up using WaitLatch to listen for SIGTERM etc., but using it in an [idle callback](http://docs.libuv.org/en/v1.x/idle.html) I don't see exactly how it "conflicts".

> You work under postgres superuser in postgres database?! not-superusers should have power rights to access net.* tables. And how access from another databases?

This was a short-term solution. The Supabase hosted database only uses the `postgres` database, and the `postgres` role is not a superuser.

**Comment by RekGRpth** [comment]
> Postgres, libcurl, and libuv, and for the latter 2 using malloc

No, libcurl may use any alloc function, see
https://github.com/RekGRpth/pg_curl/blob/39b52873b7e1bccdad81f701f15a09f42b16c327/pg_curl.c#L44-L62
and
https://github.com/RekGRpth/pg_curl/blob/39b52873b7e1bccdad81f701f15a09f42b16c327/pg_curl.c#L68

**Comment by RekGRpth** [comment]
> IIRC the start transaction dance automatically creates a transaction-local memory context, so the palloc'd memory should be freed properly.

There is no transaction in background worker in idle_cb function!

**Comment by RekGRpth** [comment]
> We did end up using WaitLatch to listen for SIGTERM etc., but using it in an [idle callback](http://docs.libuv.org/en/v1.x/idle.html) I don't see exactly how it "conflicts".

WaitLatch wait 1000 ms, and libuv loop does not work in that time.

**Comment by soedirgo** [comment]
> There is no transaction in background worker in idle_cb function!

I'm not sure what you mean - I'm talking about:
```c
    StartTransactionCommand();
    PushActiveSnapshot(GetTransactionSnapshot());
    SPI_connect();
    // ...
    SPI_finish();
    PopActiveSnapshot();
    CommitTransactionCommand();
```

> WaitLatch wait 1000 ms, and libuv loop does not work in that time

It does mean that requests aren't submitted to curl immediately (~1s delay), but libuv does not busy wait/sleep for 1000ms on *every* loop - only when it's not handling any requests.

**Comment by RekGRpth** [comment]
> I'm not sure what you mean

instead https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L486-L488 and https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L498 You may do
```c
MemoryContext oldMemoryContext = MemoryContextSwitchTo(TopMemoryContext);
char *method = TextDatumGetCString(SPI_getbinval(SPI_tuptable->vals[i], SPI_tuptable->tupdesc, 2, &isnull));
MemoryContextSwitchTo(oldMemoryContext);
```
and instead https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L85 You may do 
```c
pfree(ctx->data->method);
```
to avoid using non-postgres alloc/free

**Comment by soedirgo** [comment]
Yes, that's exactly what I said above - I could always switch to the TopMemoryContext and use palloc anywhere I'd use malloc. But I don't see why I have to, and using malloc makes it clear I'm interacting with the libcurl/libuv side rather than the Postgres side.

Also the memory allocated by `TextDatumGetCString` etc. should be deallocated along with the transaction-local memory context (see my code snippet above).

**Comment by RekGRpth** [comment]
> Postgres's event loop API is not well-documented

I studied it by source and done loop with many sockets in pg_task.

**Comment by RekGRpth** [comment]
> But I don't see why I have to

because it is a postgres plugin/extension!

**Comment by RekGRpth** [comment]
> Also the memory allocated by `TextDatumGetCString` etc. should be deallocated along with the transaction-local memory context (see my code snippet above).

But main aim is do not deallocate and use it outside

**Comment by steve-chavez** [comment]
> pg_curl with pg_task do same as pg_net things and even much more!

In this case I don't think doing more is an advantage, we really want to nail the http use case first. Just noted a recent [memory leak fix on pg_task](https://github.com/RekGRpth/pg_task/commit/e6b882618e238f05e3a3260ebf43f392ffd8b2c9), having a larger codebase(specially in C code) increases the risk of these happening. pg_net codebase is smaller and focused in contrast.

> really?! You work under postgres superuser in postgres database?!

Note that there's a comment above:

https://github.com/supabase/pg_net/blob/04dd22fb7cf267d55057deccdf70aed373dc7032/src/worker.c#L529-L530

Adding a GUC for configuring that seems simple enough.

**Comment by RekGRpth** [comment]
> Adding a GUC for configuring that seems simple enough. Could you submit a PR and help us with that?

What if database does not exist? (in pg_task it is created in this case)
